site_name: 정책과 절차
site_url: https://seonjin-qualitycontrol.github.io/policy/

theme:
  name: material
  custom_dir: overrides
  favicon: ./assets/images/clip.png

nav:
    - 내규:
      - 정관(조회용, 개정 2022년 6월 30일): ./internalPolicy/00-정관.md
      - 70 감사조서관리 규정: ./internalPolicy/70-감사조서관리 규정.md   
      - 90 품질관리규정: ./internalPolicy/90-품질관리규정.md
      - 91 품질관리규정(부록): ./internalPolicy/91-품질관리규정(부록).md
      - 92 법인내부 윤리규정 및 품질관리규정 징계 지침 : ./internalPolicy/92-법인내부 윤리규정 및 품질관리규정 징계 지침.md
      - 93 업무수임과 유지에 관한 Policy: ./internalPolicy/93-업무수임과 유지에 관한 Policy.md
      - 개정사항: ./internalPolicy/개정사항.md
    # - 정책 공지:
      # - TBD: index.md
    - 품질관리절차:
      # - 계약: 'index.md'
      - 업무품질관리검토:
        - 외부감사법 감사업무: './qualityProcedure/qualityReview.md'        
      - 발행: ./qualityProcedure/goPublic.md
      - 업무의 수행:
        - 시간: ./qualityProcedure/workingPaper.md
        - 자문: ./qualityProcedure/consultation.md
        - 조서: ./qualityProcedure/workingPaper.md
        - 기타: ./qualityProcedure/workingPaper.md
      - 성과평가: ./qualityProcedure/performanceReview.md
      - 징계: ./qualityProcedure/punishment.md
    - 기타 절차: ./qualityProcedure/workingPaper.md
    - (참고) 품질관리감리 결과:
      - 2022년 개선권고항목: ./fssReview/fr2022.md
    - (참고) Quality Update:
      - 2022.12.15. - 2023. 4. 3.: ./qualityUpdate/221215-230403.md
      - 2023. 4. 3. - 2023. 5. 8.: ./qualityUpdate/230403-230508.md

markdown_extensions:
    - toc:
        permalink: '#'
        baselevel: 1
        toc_depth: 2-6
    - attr_list
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - md_in_html
    - pymdownx.tabbed:
        alternate_style: true     
  
plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  